### Numpy (Numeric python)
수치 데이터를 처리하는 라이브러리, 고속/편리, 모든 머신러닝 라이브러리와 호환됩니다.
머신러닝을 하려면 모든 데이터는 수치로 변경되어야 하비다.
- 자연어 : 단어, 조사를 숫자로, Word2Vector
- 흑백 이미지 : 흰색 > 255, 검은색 > 0
- 컬러 이미지(RGB) : RED > (255,0,0)
- 혈액형(범주) : A, B, AB, O > (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1) - 원핫 인코딩

In [1]:
import numpy as np # 별칭(별명) 편의를 위해 붙임. 묵지적인 규칙이 있다.

In [2]:
np.arange(9) # 일련번호로 배열을 생성

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# arange 는 연산에 활용이 가능하다. 집합, Vector 느낌
np.arange(9) + np.arange(9)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [4]:
try:
    range(9) + range(9)
except:
    print('연산불가. range 와 arange 의 차이점')

연산불가. range 와 arange 의 차이점


In [7]:
# list 와의 차이점
[1, 2, 3, 4, 5] + [6, 7, 8, 9, 0]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [14]:
# list 를 numpy의 array(ndarray=Number of Dimension)로 변환
nda = np.array([1, 2, 3, 4, 5]) + np.array([6, 7, 8, 9, 0])
nda2 = np.array([12, 3, 4.5])
type(nda), len(nda), nda, nda.shape, nda.dtype, nda2.dtype

(numpy.ndarray,
 5,
 array([ 7,  9, 11, 13,  5]),
 (5,),
 dtype('int32'),
 dtype('float64'))

In [31]:
def div(a, b, point_size=10):
    x = a // b
    y = a % b
    r = x
    i = 0
    while ((y != 0) and (i < point_size)):
        i += 1
        n = y * 10
        x = n // b
        y = n % b
        r = r + (x / 10)
    return (r)

div(2, 3), 2/3

(5.999999999999999, 0.6666666666666666)