## 7장 텍스트 다루기

In [7]:
sentences = ['재밌어요. 톰홀랜드가 스파이더맨 오래 맡았으면 좋겠네요.MJ는 감정이입이 잘 안되네요 커스틴던스트가 딱이었는데'
            , '보다 중간에 나가고 싶은걸 참았다. 초반부터 중반부까지 지루해서 죽고, 중반부터 에너지괴물? 과 스파이더맨의 전투 CG로 도배. 줄거리가 너무 없다. 그냥 시끄러운 만화'
            , '살짝 유치하기도 하고 이제 이러한 스토리가 익숙해지기도 하지만 어벤져스 이후 그리웠던 마블을 다시 볼 수 있게된 것 같아서 마냥 좋았다']

In [8]:
type(sentences), len(sentences)

(list, 3)

#### BOW(Bag of Words) 단어 가방으로 전처리

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cvect = CountVectorizer()

In [11]:
cvect.fit(sentences) # 자연어에 대한 사전을 만든다.

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [12]:
cvect.vocabulary_ # 숫자는 단어의 정렬순서를 의미한다.

{'재밌어요': 33,
 '톰홀랜드가': 46,
 '스파이더맨': 18,
 '오래': 26,
 '맡았으면': 14,
 '좋겠네요': 35,
 'mj는': 1,
 '감정이입이': 2,
 '안되네요': 22,
 '커스틴던스트가': 45,
 '딱이었는데': 10,
 '보다': 15,
 '중간에': 39,
 '나가고': 6,
 '싶은걸': 21,
 '참았다': 43,
 '초반부터': 44,
 '중반부까지': 40,
 '지루해서': 42,
 '죽고': 37,
 '중반부터': 41,
 '에너지괴물': 25,
 '스파이더맨의': 19,
 '전투': 34,
 'cg로': 0,
 '도배': 9,
 '줄거리가': 38,
 '너무': 7,
 '없다': 24,
 '그냥': 4,
 '시끄러운': 20,
 '만화': 13,
 '살짝': 16,
 '유치하기도': 27,
 '하고': 47,
 '이제': 29,
 '이러한': 28,
 '스토리가': 17,
 '익숙해지기도': 31,
 '하지만': 48,
 '어벤져스': 23,
 '이후': 30,
 '그리웠던': 5,
 '마블을': 12,
 '다시': 8,
 '있게된': 32,
 '같아서': 3,
 '마냥': 11,
 '좋았다': 36}

In [13]:
len(cvect.vocabulary_)

49

In [14]:
# 지금까지 사용한 matrix는 dense_matrix <-> sparse_matrix(자연어) : 메모리 절약하기 위해서 사용
sparse_matrix = cvect.transform(sentences) # 자연어의 단어를 세는 작업을 한다.
sparse_matrix

<3x49 sparse matrix of type '<class 'numpy.int64'>'
	with 49 stored elements in Compressed Sparse Row format>

In [15]:
sparse_matrix.toarray() # sparse -> dense 로 변환

array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1]], dtype=int64)

In [21]:
from sklearn.datasets import fetch_20newsgroups

In [22]:
news = fetch_20newsgroups()

In [25]:
len(news.data), len(news.target_names)

(11314, 20)

In [26]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [34]:
idx = 2
print(news.target[idx])
print(news.target_names[news.target[idx]])
print(news.data[idx])

4
comp.sys.mac.hardware
From: twillis@ec.ecn.purdue.edu (Thomas E Willis)
Subject: PB questions...
Organization: Purdue University Engineering Computer Network
Distribution: usa
Lines: 36

well folks, my mac plus finally gave up the ghost this weekend after
starting life as a 512k way back in 1985.  sooo, i'm in the market for a
new machine a bit sooner than i intended to be...

i'm looking into picking up a powerbook 160 or maybe 180 and have a bunch
of questions that (hopefully) somebody can answer:

* does anybody know any dirt on when the next round of powerbook
introductions are expected?  i'd heard the 185c was supposed to make an
appearence "this summer" but haven't heard anymore on it - and since i
don't have access to macleak, i was wondering if anybody out there had
more info...

* has anybody heard rumors about price drops to the powerbook line like the
ones the duo's just went through recently?

* what's the impression of the display on the 180?  i could probably swing
a 18

### 전처리
- 자연어 뉴스를 배열(vector)로 변환 / BOW

In [36]:
cvect = CountVectorizer().fit(news.data)

In [38]:
len(cvect.vocabulary_), list(cvect.vocabulary_)[:5]

(130107, ['from', 'lerxst', 'wam', 'umd', 'edu'])

In [41]:
sm = cvect.transform(news.data)
sm.shape

(11314, 130107)

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
model = LogisticRegression().fit(sm, news.target)

C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\wtime\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [44]:
model.score(sm, news.target)

0.999734841788934

In [59]:
X_test = ['Hi, Major League Baseball Game, who is winner?'
         , 'I want to buy a notebook. where shoud I go? ']

In [60]:
p = model.predict(cvect.transform(X_test))
p

array([9, 4])

In [62]:
for i in p:
    print(news.target_names[i])

rec.sport.baseball
comp.sys.mac.hardware


In [63]:
sm[0].indices # 배열에서 값이 있는 곳의 위치를 알려준다.

array([  4605,  16574,  18299,  26073,  27436,  28615,  32311,  34181,
        34995,  35187,  35612,  35983,  37433,  37565,  37780,  40998,
        42876,  45295,  48618,  48620,  50111,  50527,  51730,  51793,
        56979,  56989,  57308,  62221,  63363,  64095,  65798,  66098,
        66608,  67156,  68532,  68766,  73201,  74693,  75358,  76032,
        76718,  76722,  78784,  78955,  79666,  80638,  83256,  85354,
        86001,  86580,  87620,  89362,  89860,  90252,  90379,  90686,
        90774,  92081,  94362,  95162,  96144,  98949,  99822, 101378,
       104813, 106116, 108252, 109271, 109581, 111322, 113986, 114428,
       114455, 114579, 114688, 114731, 115475, 118280, 118983, 123162,
       123292, 123796, 123984, 123989, 124031, 124931, 128026, 128402,
       128420])

In [69]:
sm[0, 128402]

2